### ISSUE TITLE
Website UI

### ISSUE THREAD

**Issue by EshanTrivedi21** [rjha27404/food_website#18]
Heyy, the website is good, but I feel there are many UI issue which I feel like fixing!
can I please be assigned this task?

Also there are a few things which would not allow this repository to be counted in as a hacktoberfest repositpory, since I am a maintainer in hacktoberfest having 22 contributors in my repo, I think I can pull a request to solve this issue as well!

@rjha27404 @Pjha72 @vishalkandu01 @suraj97303

**Comment by rjha27404** [comment]
ok

**Comment by EshanTrivedi21** [comment]
Please assign me this task @rjha27404
